name : book-it-out-ci-cd

on:
  pull_request:
    branches: [main]

env:
  MYSQL_DB: book
  MYSQL_USER: book
  MYSQL_PW: bookitout
  MYSQL_ROOT_PW: root
  JAVA_VERSION: 1.15

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PW }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PW }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit
          text: 'CI/CD have started'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      # - name : Run tests

      - name: Build Spring Project with Gradle
        run: |
          cd BookItOut
          ./gradlew clean build

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit
          text: 'SUCCESS : Spring Boot Build with Gradle'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Build and Push Docker Image
        run: |
          cd BookItOut
          docker build --platform amd64 \
          --build-arg JWT_KEY=$JWT_SECRET_KEY \
          --build-arg DB_URL=$DB_URL \
          --build-arg DB_ID=$DB_ID \
          --build-arg DB_PW=$DB_PW \
          --build-arg EMAIL_ID=$EMAIL_ID \
          --build-arg EMAIL_PW=$EMAIL_PW \
          -t jinkpark/book-it-out:v1-amd64 .
          docker push jinkpark/book-it-out:v1-amd64
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_ID: ${{ secrets.DB_ID }}
          DB_PW: ${{ secrets.DB_PW }}
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          EMAIL_PW: ${{ secrets.EMAIL_PW }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit
          text: 'SUCCESS : Pushed to Dockerhub'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name : Deploy to AWS
      # - name: Deploy React